name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  registry: "docker.io"
  reponame: "async_loop"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Branch Name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Run Auto-Semver
        id: semver
        uses: RightBrain-Networks/semver-action@1.0.0
        with:
          mode: set

      - name: Get Image Tag
        run: echo "${{ steps.semver.outputs.SEMVER_NEW_VERSION }}"